Rewrite struct sigaltstack with stack_t to avoid compile errors
This fix is needed to work around the following compile error.

./gotsan.cc:13117:22: error: aggregate 'sigaltstack handler_stack' has
incomplete type and cannot be defined
   struct sigaltstack handler_stack;
                      ^~~~~~~~~~~~~

stack_t is defined in /usr/include/asm-generic/signal.h

typedef struct sigaltstack {
        void *ss_sp;
        int ss_flags;
        size_t ss_size;
} stack_t;